# Generated by Django 5.1.6 on 2025-02-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='content_durations',
            new_name='content_duration',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='reviews',
            new_name='num_reviews',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='subscribers',
            new_name='num_subscribers',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, choices=[('Business Finance', 'Business Finance'), ('Graphic Design', 'Graphic Design'), ('Musical Instruments', 'Musical Instruments'), ('Web Development', 'Web Development')], max_length=100, null=True),
        ),
    ]
